- name: update Repo Cache
  command: "yum makecache"
  when: inventory_hostname in groups[group] 
- name: Install Packages
  command: "yum install {{ item }} -y"
  with_items:
    - krb5-server
    - krb5-libs
    - krb5-workstation
  when: inventory_hostname in groups[group] 

- name: Update kdc.conf
  template: src=templates/kdc.conf   dest=/var/kerberos/krb5kdc/kdc.conf owner=root group=root mode=0600
  when: inventory_hostname in groups[group] 

- name: Update kadm5.acl 
  template: src=templates/kadm5.acl   dest=/var/kerberos/krb5kdc/kadm5.acl owner=root group=root mode=0600
  when: inventory_hostname in groups[group] 

- name: Update krb5.conf
  template: src=templates/krb5.conf   dest=/etc/krb5.conf owner=root group=root mode=0644
  when: inventory_hostname in groups[group] 
