- name: init uma agent
  hosts: "{{ group }}"
  become: yes
  gather_facts: yes
  tasks:
  - name: Download uma package
    shell: "wget http://umon.api.service.ucloud.cn/static/umatest/uma-1.1.5-1.x86_64.rpm"
    when: (ansible_facts['os_family']|lower == 'redhat') or (ansible_facts['os_family']|lower == 'centos') 
  - name: Install uma package
    shell: "yum localinstall uma-1.1.5-1.x86_64.rpm -y"
    when: (ansible_facts['os_family']|lower == 'redhat') or (ansible_facts['os_family']|lower == 'centos')
  - name: Download uma package
    shell: "wget http://umon.api.service.ucloud.cn/static/umatest/uma_1.1.5-1_amd64.deb"
    when: (ansible_facts['os_family']|lower == 'ubuntu') or (ansible_facts['os_family']|lower == 'debian') 
  - name: Install uma package
    shell: "dpkg -i uma_1.1.5-1_amd64.deb"
    ignore_errors: yes
    when: (ansible_facts['os_family']|lower == 'ubuntu') or (ansible_facts['os_family']|lower == 'debian')
  - name: Set pkg
    shell: "apt-get -f install -y"
    when: (ansible_facts['os_family']|lower == 'ubuntu') or (ansible_facts['os_family']|lower == 'debian')
  - name: Start uma service
    shell: "service uma start"
