- name: Update Repo Cache
  command: "yum makecache"
  when: inventory_hostname in groups[group]
- name: Install Required Packages
  command: "yum install {{ item }} -y"
  with_items:
    - httpd-tools
  when: inventory_hostname in groups[group]
- name: Sync Test Data
  copy: src=files/{{ item }} dest=/home/{{ item }} owner=root mode=0755
  with_items:
    - test.json
  when: inventory_hostname in groups[group]
