- name: create dir
  shell: "mkdir -pv /data"
  when: inventory_hostname in groups[group] 
- name: login Uhub repo
  shell: "docker login -u {{ ucloud_user }} -p '{{ ucloud_password }}' uhub.service.ucloud.cn"
  when: inventory_hostname in groups[group] 
- name: pull images
  shell: "docker pull {{ prometheus_image }}"
  when: inventory_hostname in groups[group] 
- name: sync prometheus config yaml
  template: src=templates/prometheus-config.yml   dest=/data/ owner=root group=root mode=0644
  when: inventory_hostname in groups[group] 
- name: sync prometheus compose yaml
  template: src=templates/prometheus-compose.yml   dest=/data/ owner=root group=root mode=0644
  when: inventory_hostname in groups[group] 
- name: run prometheus
  shell: 'docker-compose -f /data/prometheus-compose.yml up -d'
  when: inventory_hostname in groups[group] 
